version: "3"
services:
  pg_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=selectel
      - POSTGRES_USER=selectel
      - POSTGRES_DB=selectel
    volumes:
      - dataPostgresql
    ports:
      - 5432:5432