version: "3"
services:

  client:
    image: client
    restart: on-failure
    ports:
      - 8080:8080

  db:
    image: postgres
    container_name: db
    restart: always
    volumes:
      - dataPostgresql:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - database

volumes:
  dataPostgresql: